#!/bin/bash

################################
#  This is configuration file  #
################################

# change the Paths to files or directories between the quotes "" according to your local installations 

Trinity="/usr/remote/trinityrnaseq_r2013_08_14/Trinity.pl"  # Path to Trinity ex: /home/you/trinityrnaseq_r20140413p1/Trinity
RepeatMasker="/panhome/goubert/RepeatMasker/RepeatMasker" # Path to RepeatMasker ex: /home/you/RepeatMasker/RepeatMasker
TRF="trf407b.linux64" # Path to Tandem Repeat Finder ex: /usr/local/trf407b.linux64
Blast_folder="/usr/local/bin/ncbi-blast-2.2.27+/bin/" # Path to Blast+ suite binaries folder ex: /usr/local/bin/
Parallel="/home/clement/pbil-panhome/parallel-20140622/src/parallel" # Path to GNU Parallel program
CD_HIT="/usr/remote/cd-hit-v4.6.1/cd-hit-est" # Path to cd-hit-est program
